server.port=8081

api.base-url=${API_BASE_URL:http://localhost:8080}

vapid.public-key=BIp3kUetAw4oPNGzTPGE3Cm-q706uOKf23Kvf-ZV8n_47pbHKu9VXjOMr4O0n1IGZkIolJG6HczKBLqWqVA6rqc=
vapid.private-key=AMAp5tBZbVDoXwjLqzTnq4HepMxGznN3VExEnTeNWOzs
vapid.subject=mailto:admin@jobwatch.com
