server.port=8081

api.base-url=${API_BASE_URL:http://localhost:8080}

vapid.public-key=BAbLhbqJMN9e9nJ-2VLa2u54r-o7j70PpC-nUcAqmd6KrOJF03t-IAiIZwalr9LjrOz8QyY5vIKMlxeLNMtFDhM
vapid.private-key=h_pcGcBmvQxv8mPi_i9Ni7sej3b-9za-HKVQKT0kWfc
vapid.subject=mailto:admin@jobwatch.com
