spring.application.name=api-service

# Postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobwatch}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:jobwatch}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jobwatch}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# jwt
jwt.secret=jobwatch-secret-key-this-needs-to-be-at-least-256-bits-long-for-hs256
jwt.expiration=2592000000

# jpa
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
