services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: jobwatch
      POSTGRES_USER: jobwatch
      POSTGRES_PASSWORD: jobwatch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-service:
    build: ./api-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobwatch
      SPRING_DATASOURCE_USERNAME: jobwatch
      SPRING_DATASOURCE_PASSWORD: jobwatch

  notification-service:
    build: ./notification-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - api-service
    environment:
      API_BASE_URL: http://api-service:8080
      VAPID_PUBLIC_KEY: BIp3kUetAw4oPNGzTPGE3Cm-q706uOKf23Kvf-ZV8n_47pbHKu9VXjOMr4O0n1IGZkIolJG6HczKBLqWqVA6rqc=
      VAPID_PRIVATE_KEY: AMAp5tBZbVDoXwjLqzTnq4HepMxGznN3VExEnTeNWOzs

  scraper-service:
    build: ./scraper-service
    restart: always
    depends_on:
      - redis
      - api-service
      - notification-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_BASE_URL: http://api-service:8080
      NOTIFICATION_SERVICE_URL: http://notification-service:8081
      POLL_INTERVAL_SECONDS: 60

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://jobwatch.duckdns.org
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api-service

volumes:
  postgres_data:
